#!/usr/bin/env bash
# Run the local Criterion benchmarks for the current rust-xhttp implementation.
#
# Usage:
#   scripts/bench.sh
# Env:
#   REPORT=docs/benchmark-latest.md
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPORT="${REPORT:-$ROOT/docs/benchmark-latest.md}"

cd "$ROOT"
mkdir -p "$(dirname "$REPORT")" "$ROOT/local/artifacts"

OUT="$ROOT/local/artifacts/criterion-$(date -u +%Y%m%dT%H%M%SZ).log"
cargo bench --bench kernels --bench geo | tee "$OUT"

{
  echo "# Benchmark report"
  echo
  echo "Generated by \`scripts/bench.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
  echo
  echo "- Project: \`rust-xhttp\`"
  echo "- Command: \`cargo bench --bench kernels --bench geo\`"
  echo "- Full output: \`$OUT\`"
} > "$REPORT"

echo
echo "=== report written to $REPORT ==="
