#!/usr/bin/env bash
# Local rust-xhttp benchmark smoke: run the XHTTP E2E path and the local benches.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPORT="${REPORT:-$ROOT/docs/benchmark-latest.md}"
cd "$ROOT"
mkdir -p "$ROOT/local/artifacts" "$(dirname "$REPORT")"

echo "=== local XHTTP E2E ==="
"$ROOT/scripts/m7_e2e.sh"

echo
echo "=== criterion kernels ==="
cargo bench --bench kernels | tee "$ROOT/local/artifacts/bench-ab-kernels.log"

{
  echo "# Benchmark latest"
  echo
  echo "Generated by \`scripts/bench_ab.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
  echo
  echo "- Local XHTTP E2E: passed"
  echo "- Kernel bench log: \`local/artifacts/bench-ab-kernels.log\`"
} > "$REPORT"

echo "report: $REPORT"
